### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by alexpi** [jsebrech/plainvanilla#9]
Hello,

How can we have cache busting of static assets in a buildless workflow? I know some hosting platforms do this automatically (Netlify, Vercel etc), but is there a solution for simpler hosting environments?

**Comment by jsebrech** [comment]
Thank you for this question!

Some thoughts:

- Query parameters can always be used to bust the cache, so as long as all references to a file are updated with a ?v=2 parameter the new version of the file will be served.
- Do what github pages does: set Cache-Control: max-age = 600 for the whole website. The user can get assets that are up to 10 minutes out of date, but for a static site that doesn't really matter. This is what I do for plain vanilla.
- Use something like Cloudflare to set per asset caching rules. Set short caching on small resources like HTML and JS files (10 minutes), long caching on large resources like images. If an image for some reason needs to change, add a cache-busting query parameter to references to that image.
- For full control, use a service worker. The site will be served from the local cache and the service worker can decide when to force a redownload by discarding the cache and adding cache-busting query parameters transparently.

I'll think about it some more and turn this into a blog post.

**Comment by jsebrech** [comment]
I finally had a chance to write it up as a blog post. I'll be closing this issue now.

https://plainvanillaweb.com/blog/articles/2024-12-16-caching-vanilla-sites/
